name: pocket_gm_generator
description: A comprehensive football player generator for creating realistic players with authentic names, backgrounds, and attributes for pro football simulation games.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
